AppBundle\Entity\Projects:
    properties:
        name:
            - NotBlank: ~
        price:
            - NotBlank: ~
            - Type: 
               type: integer
               message: The value {{ value }} is not a valid {{ type }}.
        description:
            - NotBlank: ~